"""init tables

Revision ID: 5d918e3430d2
Revises: a8c229d9c088
Create Date: 2026-03-30 21:31:34.454607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d918e3430d2'
down_revision: Union[str, Sequence[str], None] = 'a8c229d9c088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_guide_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'senior_guides', ['guide_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_guide_id_fkey'), 'bookings', 'users', ['guide_id'], ['id'])
    # ### end Alembic commands ###
