"""init tables

Revision ID: 65f81a54f364
Revises: 5d918e3430d2
Create Date: 2026-03-31 12:08:10.669277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f81a54f364'
down_revision: Union[str, Sequence[str], None] = '5d918e3430d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_sessions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('call_sessions', sa.Column('reconnect_attempts', sa.Integer(), nullable=True))
    op.add_column('call_sessions', sa.Column('refund_flag', sa.Boolean(), nullable=True))
    op.add_column('call_sessions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'call_sessions', ['booking_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call_sessions', type_='unique')
    op.drop_column('call_sessions', 'created_at')
    op.drop_column('call_sessions', 'refund_flag')
    op.drop_column('call_sessions', 'reconnect_attempts')
    op.drop_column('call_sessions', 'status')
    # ### end Alembic commands ###
