"""init tables

Revision ID: a8c229d9c088
Revises: cdd1c90bec1a
Create Date: 2026-03-30 19:52:06.876554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c229d9c088'
down_revision: Union[str, Sequence[str], None] = 'cdd1c90bec1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('senior_guides', sa.Column('aadhaar_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('senior_guides', 'aadhaar_number')
    # ### end Alembic commands ###
