"""init tables

Revision ID: b031fb17cc21
Revises: d0f3a6d9a5a3
Create Date: 2026-03-31 13:39:26.989207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b031fb17cc21'
down_revision: Union[str, Sequence[str], None] = 'd0f3a6d9a5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('guide_id', sa.Integer(), nullable=True),
    sa.Column('faculty_rating', sa.Integer(), nullable=True),
    sa.Column('placement_rating', sa.Integer(), nullable=True),
    sa.Column('infrastructure_rating', sa.Integer(), nullable=True),
    sa.Column('hidden_fees', sa.String(), nullable=True),
    sa.Column('strict_attendance', sa.String(), nullable=True),
    sa.Column('ragging_situation', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['guide_id'], ['senior_guides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('college_feedback')
    op.drop_table('guide_ratings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guide_ratings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guide_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_calls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wallet_balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_earned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('honesty', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recommend', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('guide_ratings_booking_id_fkey')),
    sa.ForeignKeyConstraint(['guide_id'], ['senior_guides.id'], name=op.f('guide_ratings_guide_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('guide_ratings_pkey')),
    sa.UniqueConstraint('booking_id', name=op.f('guide_ratings_booking_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('college_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('faculty_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('placement_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('infrastructure_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hidden_fees', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('strict_attendance', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ragging', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('college_feedback_booking_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('college_feedback_pkey'))
    )
    op.drop_table('college_feedbacks')
    # ### end Alembic commands ###
