"""init tables

Revision ID: d0f3a6d9a5a3
Revises: 8fb986dbc44a
Create Date: 2026-03-31 13:31:20.482718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f3a6d9a5a3'
down_revision: Union[str, Sequence[str], None] = '8fb986dbc44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('senior_guides', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('senior_guides', sa.Column('total_calls', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('senior_guides', 'total_calls')
    op.drop_column('senior_guides', 'rating')
    # ### end Alembic commands ###
