"""init tables

Revision ID: f3ff804ba0d9
Revises: 3f347ecc1914
Create Date: 2026-03-31 15:44:35.638435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3ff804ba0d9'
down_revision: Union[str, Sequence[str], None] = '3f347ecc1914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    op.drop_table('colleges')
    op.drop_table('availability_slots')
    op.drop_table('guide_ratings')
    op.drop_table('branches')
    op.add_column('bookings', sa.Column('reminder_30_sent', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('reminder_5_sent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'reminder_5_sent')
    op.drop_column('bookings', 'reminder_30_sent')
    op.create_table('branches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('college_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('branches_college_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('branches_pkey'))
    )
    op.create_table('guide_ratings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('guide_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_calls', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wallet_balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_earned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('honesty', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recommend', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('guide_ratings_booking_id_fkey')),
    sa.ForeignKeyConstraint(['guide_id'], ['senior_guides.id'], name=op.f('guide_ratings_guide_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('guide_ratings_pkey')),
    sa.UniqueConstraint('booking_id', name=op.f('guide_ratings_booking_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('availability_slots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guide_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_booked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guide_id'], ['senior_guides.id'], name=op.f('availability_slots_guide_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('availability_slots_pkey'))
    )
    op.create_table('colleges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('colleges_country_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('colleges_pkey')),
    sa.UniqueConstraint('name', name=op.f('colleges_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('countries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('countries_pkey')),
    sa.UniqueConstraint('name', name=op.f('countries_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
